chore: Fix Attachments and Supplement storage definitions
Indicio-tech/aries-cloudagent-python pull request #90
Opened 2022-09-14 18:27 UTC by frostyfrog

This should fix the issue that @dbluhm mentioned

2022-09-14 18:29 UTC, dbluhm requested changes

2022-09-14 18:29 UTC, dbluhm commented on aries_cloudagent/protocols/present_proof/v2_0/models/pres_exchange.py
>      supplements = fields.Nested(
Need to set `many` to `True`

2022-09-14 18:29 UTC, dbluhm commented on aries_cloudagent/protocols/present_proof/v2_0/models/pres_exchange.py
> +    attachments = fields.Nested(
Same

2022-09-14 21:05 UTC, frostyfrog commented
The above changes from Peter were not meant to be a part of this PR. I will work to get those separated into another PR

2022-09-14 21:52 UTC, frostyfrog commented
Force push removed the previous two commits. I have moved those to a separate branch, feature/credential-attachments-verifier-tests

2022-09-15 15:24 UTC, dbluhm approved these changes
Looks good, thanks!

2022-09-15 15:29 UTC, merged